- dnGREP.Common.UI/BookmarksForm.cs
- dnGREP.WPF/Dictionaries/CustomTemplates.xaml
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/Views/MainViewEx.xaml
- #261 Making the star button easier to click
- #262 Clearing star when deleting its bookmark
- UI cleanup along the way.
> Bookmark ui changes

- Tests/GrepCoreTest.cs
- Tests/Tests.csproj
- Tests/packages.config
- dnGREP.Common/Utils.cs
- dnGREP.WPF/Views/MainView.xaml
> Escape chars

- dnGREP.WPF/Views/MainView.xaml
The content of a few text boxes wasn't correctly aligned, and one had additionally a wrong upper margin.
> Fix content alignment and margin of text boxes

- dnGREP.Common/Utils.cs
- dnGREP.Engines/GrepCore.cs
> Change utf-8 encoder to match original file byte order mark

- dnGREP.WPF/MVHelpers/ObservableGrepSearchResults.cs
- dnGREP.WPF/ThemedControls/Button.xaml
- dnGREP.WPF/ThemedControls/CheckBox.xaml
- dnGREP.WPF/ThemedControls/DatePicker.xaml
- dnGREP.WPF/ThemedControls/ScrollViewer.xaml
- dnGREP.WPF/ViewModels/TestPatternViewModel.cs
Addresses #341 Focus Visual error and #139 test tool output format
> Focus Visual and Test Tool fix

- dnGREP.ArchiveEngine/GrepEngineArchive.cs
- dnGREP.Common/OpenFileArgs.cs
- dnGREP.Common/Utils.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/Views/OptionsView.xaml
Add new %match and %column options to command line when opening custom editor
> Custom editor arguments

- dnGREP.Common/Ude.Core/CharDistributionAnalyser.cs
- dnGREP.Common/Utils.cs
Fix table size constant
Add valid string checks to GetBaseFolder
> Fixed two index out of bounds exceptions

- Tests/BookmarkTest.cs
- dnGREP.Common/BookmarkLibrary.cs
- dnGREP.WPF/ThemedControls/CheckBox.xaml
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/BookmarksViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/ViewModels/ViewModelBase.cs
- dnGREP.WPF/Views/BookmarkDetailWindow.xaml
- dnGREP.WPF/Views/BookmarkDetailWindow.xaml.cs
- dnGREP.WPF/Views/MainView.xaml
add path references to bookmark
add additional search parameters to bookmark
add new button to main UI for folder association
> associate bookmark with folder

- dnGREP.WPF/MVHelpers/ValidationColorConverter.cs
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/TestPatternViewModel.cs
- dnGREP.WPF/Views/TestPatternView.xaml
- dnGREP.WPF/Views/TestPatternView.xaml.cs
- dnGREP.WPF/dnGREP.WPF.csproj
Update layout
Add Boolean Operators
Auto search and replace
> Test window update

- Tests/GrepCoreTest.cs
- dnGREP.Engines/GrepEngineBase.cs
- dnGREP.WPF/MVHelpers/ObservableGrepSearchResults.cs
- dnGREP.WPF/MVHelpers/PreviewHighlighter.cs
- dnGREP.WPF/MVHelpers/ReplaceViewHighlighter.cs
Fix problem with highlight if newline char is include in match
Add tests
> Improve handling of different newlines

- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/MVHelpers/FileDragDropHelper.cs
- dnGREP.WPF/UserControls/ResultsTree.xaml.cs
> prevent drop onto main window from the results tree

- dnGREP.Common/Utils.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/PreviewViewModel.cs
> change file filter order

- DockFloat/FloatWindow.cs
- dnGREP.WPF/Controls/ThemedWindow.cs
- dnGREP.WPF/Views/MainView.xaml.cs
Add HookProc to Floating window
catch overflow exception in all application windows
> Moved HookProc to base class

- Tests/UtilsTest.cs
- dnGREP.Common/GrepMatch.cs
- dnGREP.Common/Utils.cs
- dnGREP.Engines/GrepEngineBase.cs
- dnGREP.WPF/DesignTimeData/DesignTimeData.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
> 434 report or clauses

- Tests/GrepCoreTest.cs
- Tests/IgnoreIfNotAdministratorTheory.cs
- Tests/Tests.csproj
- Tests/UtilsTest.cs
- dnGREP.Common/BookmarkLibrary.cs
- dnGREP.Common/FileFilter.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/SafeDirectory.cs
- dnGREP.Common/Utils.cs
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/BookmarksViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/SearchReplaceCriteria.cs
- dnGREP.WPF/Views/BookmarkDetailWindow.xaml
- dnGREP.WPF/Views/MainView.xaml
save in user settings and bookmarks
> add file filter to follow symbolic links

- Tests/Files/TestCase18/test1.xml
- Tests/Files/TestCase18/test10.xml
- Tests/Files/TestCase18/test2.xml
- Tests/Files/TestCase18/test3.xml
- Tests/Files/TestCase18/test4.xml
- Tests/Files/TestCase18/test5.xml
- Tests/Files/TestCase18/test6.xml
- Tests/Files/TestCase18/test7.xml
- Tests/Files/TestCase18/test8.xml
- Tests/Files/TestCase18/test9.xml
- Tests/GrepCoreTest.cs
- dnGREP.Engines/GrepEngineBase.cs
> Fix for XPath search with comments in file.

- DockFloat/DockSite.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.WPF/MVHelpers/DockSiteVisibilityConverter.cs
- dnGREP.WPF/Properties/LayoutProperties.cs
- dnGREP.WPF/Properties/Settings.Designer.cs
- dnGREP.WPF/Properties/Settings.settings
- dnGREP.WPF/ThemedControls/PreviewControl.xaml
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/Views/MainView.xaml.cs
- dnGREP.WPF/app.config
- dnGREP.WPF/dnGREP.WPF.csproj
add context menu to choose right or bottom dock site
add properties to save/restore
modify visibility trigger to make only one dock site visible
> add second dock site on bottom

- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/dnGREP.WPF.csproj
> Set library path for 7zip

- dnGREP.WPF/Controls/MultilineComboBox.cs
- dnGREP.WPF/ThemedControls/ComboBox.xaml
- dnGREP.WPF/ThemedControls/CustomTemplates.xaml
select the multiline template only for the multiline comboBox
> add control templates for combo textbox

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/Utils.cs
- dnGREP.Engines/GrepCore.cs
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
add flag and checkbox enable feature, save and restore state
> add capture group search

- dnGREP.Engines/GrepCore.cs
log invalid regular expressions
> add flag to ignore case

- DockFloat/Extensions.cs
- dnGREP.Common/NativeMethods.cs
- dnGREP.Common/Utils.cs
- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/AppTheme.cs
- dnGREP.WPF/UserControls/ResultsTree.xaml.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/TestPatternViewModel.cs
- dnGREP.WPF/Views/MainView.xaml.cs
change message box titles to include "dnGrep"
add log directory to error messages
skip window positioning if main window is not visible
add check to ensure window width is positive
> 500 error message

- AssemblyVersionCommon.cs
- dnGREP.Setup/Product.wxs
- dnGREP.Setup/Variables.wxi
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/OptionsView.xaml
changed key used to check if user can add or remove explorer context menu
changed 'startup accelerator' to 'check for dnGrep updates at Windows startup'
removed run at startup from installer
changed text for Windows Explorer integration installer option
> 498 admin options

- dnGREP.WPF/ThemedControls/FloatWindow.xaml
- dnGREP.WPF/ThemedControls/ThemedWindow.xaml
- dnGREP.WPF/Themes/DarkBrushes.xaml
- dnGREP.WPF/Themes/LightBrushes.xaml
- dnGREP.WPF/Themes/Sunset.xaml
Add triggers to windows
Also dim the app icon when inactive
> 513: Add named brushed for inactive caption

- dnGREP.Engines/GrepCore.cs
add try/catch for file not found errors
> 541 detect file encoding error

- dnGREP.Common/Extensions.cs
- dnGREP.Common/FileData.cs
- dnGREP.Common/Utils.cs
add date and size filters to Everything search string
fix bug in FileData blocking Everything file info
> 545-Everything date filter

- dnGREP.Common/Utils.cs
to use less than and greater than for single date limits
> change Everything date filter

- dnGREP.Everything/EverythingSearch.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/MainViewModel.cs
Report missing files on search complete.
> Add test for valid drives and files in Everything search.

- dnGREP.Localization/ResxFile.cs
- dnGREP.WPF/MVHelpers/ObservableGrepSearchResults.cs
- dnGREP.WPF/UserControls/ResultsTree.xaml
- dnGREP.WPF/ViewModels/MainViewModel.cs
three addition fixes/enhancements for localization
> 528 localization 7

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/Utils.cs
- dnGREP.Engines/GrepEngineHex.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/MVHelpers/ObservableGrepSearchResults.cs
- dnGREP.WPF/UserControls/ResultsTree.xaml
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/OptionsView.xaml
Modify results tree formatting
> Add option for hex result line length

- DockFloat/DockFloat.csproj
- DockFloat/Extensions.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF.sln
- dnGREP.WPF/ThemedControls/TextBox.xaml
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/ViewModels/ReplaceViewModel.cs
- dnGREP.WPF/Views/OptionsView.xaml
- dnGREP.WPF/Views/ReplaceWindow.xaml
- dnGREP.WPF/Views/ReplaceWindow.xaml.cs
Add hack to TextBox.xaml to work around XAML designer error
> Add layout option for Replace window

- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/BookmarksViewModel.cs
- dnGREP.WPF/Views/BookmarksWindow.xaml
> Fix bookmark section index

- TestLocalizedStrings/TestStringsViewModel.cs
- dnGREP.Localization/TranslationSource.cs
- dnGREP.WPF/Views/OptionsView.xaml
> update translate URL

- AssemblyInfoCommon.cs
- AssemblyVersionCommon.cs
- README.md
- TestLocalizedStrings/Properties/AssemblyInfo.cs
- TestLocalizedStrings/TestLocalizedStrings.csproj
- appveyor.yml
- dnGREP.Setup/Variables.wxi
update appveyor properties
update version
update copyright year
> Add SignPath to GitHub main page

- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
Change to not clear history lists to avoid unwanted changes to properties
> Folder bookmark re-applied after closing Options

- dnGREP.Engines/GrepEngineBase.cs
add test for escaped character when checking for regex pattern ending in dot
> add test for escaped character

- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/CommandLineArgs.cs
- dnGREP.WPF/Views/MainView.xaml.cs
add type safe access to view model
> filter empty arguments

- TestLocalizedStrings/TestStringsViewModel.cs
- dnGREP.Localization/AddingTranslations.md
- dnGREP.Localization/Properties/Resources.es.resx
- dnGREP.Localization/ResxFile.cs
- dnGREP.Localization/TranslationSource.cs
- dnGREP.Localization/dnGREP.Localization.csproj
- dnGREP.Setup/Fragments/AppFragment.wxs
Currently translated at 100.0% (552 of 552 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/es/
> Translated using Weblate (Spanish)

- dnGREP.WPF/MVHelpers/ObservableGrepSearchResults.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
modify to make code consistent
> Fix for missing character

- dnGREP.Common/BookmarkLibrary.cs
- dnGREP.Common/ConfigurationTemplate.cs
- dnGREP.Common/FileFilter.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/Utils.cs
- dnGREP.Engines/GrepCore.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/BookmarksViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/Views/BookmarkDetailWindow.xaml
- dnGREP.WPF/Views/MainView.xaml
add filter to skip reading cloud storage files not already downloaded
> Skip cloud storage files

- dnGREP.OpenXmlEngine/ListManager.cs
> Read docx file bug

- ICSharpCode.AvalonEdit/CodeCompletion/CompletionWindowBase.cs
- ICSharpCode.AvalonEdit/Document/DocumentLineTree.cs
- ICSharpCode.AvalonEdit/Document/TextAnchorTree.cs
- ICSharpCode.AvalonEdit/Editing/Caret.cs
- ICSharpCode.AvalonEdit/Editing/SelectionMouseHandler.cs
- ICSharpCode.AvalonEdit/Editing/TextArea.cs
- ICSharpCode.AvalonEdit/Editing/TextAreaAutomationPeer.cs
- ICSharpCode.AvalonEdit/Editing/TextRangeProvider.cs
- ICSharpCode.AvalonEdit/Folding/FoldingSection.cs
- ICSharpCode.AvalonEdit/Highlighting/HighlightingColorizer.cs
- ICSharpCode.AvalonEdit/Highlighting/HtmlClipboard.cs
- ICSharpCode.AvalonEdit/Rendering/HeightTree.cs
- ICSharpCode.AvalonEdit/Rendering/TextView.cs
- ICSharpCode.AvalonEdit/Rendering/VisualLineTextSource.cs
- ICSharpCode.AvalonEdit/TextEditorAutomationPeer.cs
- ICSharpCode.AvalonEdit/Utils/ExtensionMethods.cs
- SevenZip/SevenZipExtractor.cs
- dnGREP.WPF/Views/PreviewControl.xaml.cs
Bug fix for error when changing files in the preview window with the preview window search panel open
> 658 match indicator

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModelProps.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/ViewModels/PreviewViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/Views/OptionsView.xaml
- dnGREP.WPF/Views/PreviewControl.xaml
- dnGREP.WPF/dnGREP.WPF.csproj
Add options to allow users to set visibility on main and preview window controls
> Control visibility personalization options

- dnGREP.Common/GrepSearchResult.cs
- dnGREP.WPF/MVHelpers/LazyResultsList.cs
fix bug using context line counts without checking ShowLinesInContext flag
> 703 show context lines

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/ReplaceDef.cs
- dnGREP.Common/Utils.cs
- dnGREP.Engines/GrepCore.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/ReplaceViewModel.cs
- dnGREP.WPF/Views/ReplaceWindow.xaml
add user option to keep previous modified date
> #708 last modified date

- dnGREP.Common/Utils.cs
with everything search, skip archive files if include archive is not set
> #718 Everything exclude archives

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/UserControls/MultiSelectTreeView.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/Views/OptionsView.xaml
add option to maximize on search
> add maximize results panel button and key

- Tests/StorageTest.cs
- Tests/UtilsTest.cs
- dnGREP.Common/Extensions.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/Views/PreviewControl.xaml.cs
- dnGREP.WPF/Views/ReplaceWindow.xaml.cs
update settings to remove binary data
binary formatter to be removed in a future release
> Setting file update

- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/UserControls/ResultsTree.xaml
- dnGREP.WPF/UserControls/ResultsTree.xaml.cs
- dnGREP.WPF/Views/RenameWindow.xaml
- dnGREP.WPF/Views/RenameWindow.xaml.cs
initialize rename with current file name
move error strings to resource
> 757: add move files to recycle bin

- dnGREP.Localization/Properties/Resources.zh-CN.resx
Currently translated at 100.0% (820 of 820 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/zh_Hans/
> Translated using Weblate (Chinese (Simplified))

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Engines/GrepCore.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF.sln
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/OptionsView.xaml
- dnGREP.WPF/app.config
log number of parallel tasks
enable info logging to file
> add MaxDegreeOfParallelism option setting

- dnGREP.Common/Enums.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/MostRecentlyUsed.cs
- dnGREP.Common/dnGREP.Common.csproj
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/Controls/SplitButton.cs
- dnGREP.WPF/Controls/ThemedWindow.cs
- dnGREP.WPF/MVHelpers/Messenger.cs
- dnGREP.WPF/MVHelpers/ObservableGrepSearchResults.cs
- dnGREP.WPF/SystemSymbols.cs
- dnGREP.WPF/ThemedControls/Button.xaml
- dnGREP.WPF/ThemedControls/SplitButton.xaml
- dnGREP.WPF/ThemedControls/ThemedWindow.xaml
- dnGREP.WPF/ThemedControls/ToggleButton.xaml
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/MRUViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/ViewModels/PathBookmark.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/dnGREP.WPF.csproj
add pin and delete buttons to most recently used combo boxes
> 836 folder history

- SevenZip/FileChecker.cs
- SevenZip/Formats.cs
- SevenZip/LibraryManager.cs
- SevenZip/SevenZipBase.cs
- SevenZip/SevenZipCompressor.cs
- SevenZip/StreamWrappers.cs
merge changes from squid-box/sevenzipsharp
> Seven zip update

- dnGREP.Localization/Properties/Resources.ru.resx
Currently translated at 99.1% (829 of 836 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/ru/
> Translated using Weblate (Russian)

- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/Controls/TextBoxCommands.cs
- dnGREP.WPF/ThemedControls/TextBox.xaml
- dnGREP.WPF/Views/BookmarkDetailWindow.xaml.cs
- dnGREP.WPF/Views/MainView.xaml.cs
- dnGREP.WPF/Views/OptionsView.xaml.cs
- dnGREP.WPF/Views/RenameWindow.xaml.cs
- dnGREP.WPF/Views/TestPatternView.xaml.cs
- dnGREP.WPF/dnGREP.WPF.csproj
add lowercase and uppercase menu items
> add custom textbox context menu

- .github/workflows/winget.yml
* https://github.com/vedantmgoyal2009/winget-releaser/issues/147
> Update winget-releaser to v2

- dnGREP.WPF/ViewModels/BookmarksViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/Views/BookmarksWindow.xaml.cs
Save bookmarks when hiding window.
Add handler to close window on application exit
> Hide bookmarks window on alt+F4 and titlebar close.

- dnGREP.Common/GrepApplicationSettings.cs
Issue was a type that changed from nullable bool to bool.
> Add try/catch around converting settings values to capture bad data.

- ICSharpCode.AvalonEdit/Rendering/BackgroundGeometryBuilder.cs
> Don't highlight empty rects

- dnGREP.Localization/Properties/Resources.bg.resx
- dnGREP.Setup/Fragments/Dotnet.wxs
Currently translated at 100.0% (856 of 856 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/bg/
> Translated using Weblate (Bulgarian)

- dnGREP.WPF/ThemedControls/PreviewControl.xaml
- dnGREP.WPF/ViewModels/DockViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/PreviewViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/Views/MainView.xaml.cs
- dnGREP.WPF/Views/PreviewControl.xaml
keep the previous context menu items from the dock site, and add the Copy command
> add context menu for the preview text area

- Tests/GrepCoreTest.cs
- Tests/StorageTest.cs
- Tests/UtilsTest.cs
- dnGREP.Common/GrepApplicationSettings.cs
and change n…ullable bool to same
Add test and fix code warnings in tests
> Fix for handling old serialization of nullable DateTime

- dnGREP.Common/FileFilter.cs
- dnGREP.Engines/ArchiveEngine.cs
- dnGREP.Engines/GrepCore.cs
- dnGREP.Engines/GrepEngineBase.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/TestPatternViewModel.cs
Use for search and replace.
Add static default for FileFilter
> Set the MatchTimeout at the start of the search

- dnGREP.Common.UI/CustomMessageBox.xaml
- dnGREP.Common.UI/CustomMessageBox.xaml.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/Utils.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModelScripts.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/MainView.xaml.cs
- dnGREP.WPF/Views/OptionsView.xaml
and warning dialog for replace
> add confirmation dialogs for search and scripts

- dnGREP.WPF/ViewModels/OptionsViewModel.cs
> 958 use the assembly location to find the exe file

- dnGREP.WPF/ViewModels/MenuItemViewModel.cs
> #969: fix bug turning folders into separators; fix accelerator key 

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.WPF/MVHelpers/DataGridColumnOrderBehaviour.cs
- dnGREP.WPF/MVHelpers/DataGridColumnWidthBehaviour.cs
- dnGREP.WPF/Properties/LayoutProperties.cs
- dnGREP.WPF/Views/BookmarksWindow.xaml
- dnGREP.WPF/Views/BookmarksWindow.xaml.cs
- dnGREP.WPF/Views/MainView.xaml.cs
save and restore column order and widths, widow size, state and location
> #970 Bookmarks window - save and restore 

- dnGREP.Common/ConfigurationTemplate.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/Utils.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/OptionsView.xaml
Add new editors to the configuration template
> #984 Escape quotes in the %match argument

- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/CopyCommand.cs
add check and error message for match failure
> 971 - make copy command regex case insensitive

- ICSharpCode.AvalonEdit/Rendering/FormattedTextElement.cs
- dnGREP.Common/GrepMatch.cs
- dnGREP.WPF/MVHelpers/BigEllipsisColorizer.cs
- dnGREP.WPF/MVHelpers/ReplaceViewHighlighter.cs
- dnGREP.WPF/MVHelpers/TruncateLongLines.cs
- dnGREP.WPF/Themes/DarkBrushes.xaml
- dnGREP.WPF/Themes/LightBrushes.xaml
- dnGREP.WPF/Themes/Sunset.xaml
- dnGREP.WPF/ViewModels/ReplaceViewModel.cs
- dnGREP.WPF/Views/PreviewControl.xaml.cs
- dnGREP.WPF/Views/ReplaceWindow.xaml.cs
to work around performance bug in wpf
> #992 - add class to stop rendering lines over 8K characters

- dnGREP.PdfEngine/GrepEnginePdf.cs
change to read the temp file just once
> 967 - run test for no searchable text on all pdf files

- Tests/UtilsTest.cs
- dnGREP.WPF/CommandLineArgs.cs
- dnGREP.WPF/CopyCommand.cs
cannot support unquoted paths with spaces
> 991 - revert some of the command line parser changes

- dnGREP.Localization/Properties/Resources.ja.resx
Currently translated at 96.9% (905 of 933 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/ja/
> Translated using Weblate (Japanese)

- dnGREP.Common/FileData.cs
- dnGREP.WPF/UserControls/ResultsTree.xaml
- dnGREP.WPF/Views/MainView.xaml.cs
in the file info tooltip and the date time picker control
> 1011 - fix the date time formatting

- dnGREP.Common/GrepApplicationSettings.cs
fix for settings load/upgrade errors
> 1027 settings

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/UserControls/ContextResultsTree.xaml
- dnGREP.WPF/UserControls/ContextResultsTree.xaml.cs
- dnGREP.WPF/UserControls/ResultsTree.xaml
- dnGREP.WPF/UserControls/ResultsTree.xaml.cs
- dnGREP.WPF/ViewModels/GrepSearchResultsViewModel.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/Views/MainView.xaml.cs
- dnGREP.WPF/Views/OptionsView.xaml
Avoid horizontal scrolling when stepping through results.
Add sticky scrolling to results tree.
> 1034 results tree scrolling

- Tests/GrepCoreTest.cs
- Tests/UtilsTest.cs
- dnGREP.Common/GrepCaptureGroup.cs
- dnGREP.Common/GrepMatch.cs
- dnGREP.Common/Utils.cs
- dnGREP.Engines/GrepEngineBase.cs
- dnGREP.WPF/ViewModels/GrepSearchResultsViewModel.cs
fix for group spanning multiple lines
> #1069 - fix for group highlight with windows newline

- dnGREP.Common/GitUtil.cs
Add the .git directory to the set of directories to ignore and .gitignore to the set of files to ignore.
> #1076 - gitignore

- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/ViewModels/MainViewModelScripts.cs
- dnGREP.WPF/Views/MainView.xaml.cs
Queue command line script and search to run after the main window is fully initialized.
> #1086 fix for saving bad window layout

- SevenZip/Formats.cs
- SevenZip/SevenZipBase.cs
- SevenZip/SevenZipExtractor.cs
- SevenZip/StreamWrappers.cs
plus two unmerged pull requests
> merge final changes from squid-box archived repo

- dnGREP.Localization/Properties/Resources.de.resx
Currently translated at 80.2% (775 of 966 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/de/
> Translated using Weblate (German)

- Tests/GrepCoreTest.cs
- dnGREP.Common/Enums.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/PauseCancelToken.cs
- dnGREP.Engines/GrepCore.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ThemedControls/Menu.xaml
- dnGREP.WPF/ViewModels/BaseMainViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModelProps.cs
- dnGREP.WPF/ViewModels/MainViewModelScripts.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/Views/OptionsView.xaml
Change stop after first match to be user variable
Remove stopafterfirstmatch setting
> #1090 Add user variable auto pause search

- Tests/GrepCoreTest.cs
- dnGREP.Common/GrepSearchResult.cs
- dnGREP.Engines/GrepEngineBase.cs
- dnGREP.WPF/MVHelpers/LazyResultsList.cs
- dnGREP.WPF/UserControls/ResultsTree.xaml
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/TestPatternViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
use ShowLinesInContext to toggle visibility
> #1135 read and cache lines before/lines after

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.WPF/MVHelpers/ChromeButtonVisibility.cs
- dnGREP.WPF/Properties/LayoutProperties.cs
- dnGREP.WPF/ThemedControls/ThemedWindow.xaml
- dnGREP.WPF/Views/BookmarkDetailWindow.xaml
- dnGREP.WPF/Views/OptionsView.xaml
- dnGREP.WPF/Views/OptionsView.xaml.cs
- dnGREP.WPF/Views/TestPatternView.xaml
Remove the minimize button from modal dialogs
> #1144 Options dialog: make resizable

- dnGREP.WPF/ViewModels/MainViewModelScripts.cs
remove code trying to quote paths
fix for showing error on invalid path
> 1185 scripting

- make-msix.ps1
> change path to makeappx.exe

- dnGREP.WPF/UserControls/ResultsTree.xaml
to reduce the top selection deadband
> 1199 Results Tree: reduce border thickness on tree view item

- Tests/UtilsTest.cs
- dnGREP.Common/ArchiveDirectory.cs
- dnGREP.Common/GitUtil.cs
- dnGREP.Common/IO/FileSystemEntryInfo.cs
- dnGREP.Common/IO/FindFileSystemEntryInfo.cs
- dnGREP.Common/SafeDirectory.cs
- dnGREP.Common/Utils.cs
- dnGREP.WPF/ViewModels/GrepSearchResultsViewModel.cs
Change show archive extensions are added
Fix tree binding error
> #1210 remove double directory iteration when applying file filters

- SevenZip/SevenZip.csproj
- TestLocalizedStrings/TestLocalizedStrings.csproj
- Tests/Tests.csproj
- dnGREP.Common.UI/dnGREP.Common.UI.csproj
- dnGREP.Common/dnGREP.Common.csproj
- dnGREP.DockFloat/dnGREP.DockFloat.csproj
- dnGREP.Engines/dnGREP.Engines.csproj
- dnGREP.Everything/dnGREP.Everything.csproj
- dnGREP.Localization/dnGREP.Localization.csproj
- dnGREP.OpenXmlEngine/dnGREP.OpenXmlEngine.csproj
- dnGREP.PdfEngine/dnGREP.PdfEngine.csproj
- dnGREP.WPF/dnGREP.WPF.csproj
- dnGREP.WordEngine/dnGREP.WordEngine.csproj
> Revert .net 9 NuGet packages back to 8

- dnGREP.Localization/Properties/Resources.uk.resx
Currently translated at 30.9% (314 of 1014 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/uk/
> Translated using Weblate (Ukrainian)

- appveyor.yml
- dnGREP.Setup/Fragments/Dotnet.wxs
- dotnet-install.ps1
> update to .NET 8.0.12 (8.0.405)

- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/MainView.xaml.cs
- dnGREP.WPF/Views/OptionsView.xaml
Process command line in main window and show errors 
Renamed settings key
Updated Options dialog
> Changed to pass whole command line to singleton

- ICSharpCode.AvalonEdit/ICSharpCode.AvalonEdit.csproj
- ICSharpCode.AvalonEdit/TextEditor.cs
- dnGREP.Common/BookmarkLibrary.cs
- dnGREP.Common/CompareFolders.cs
- dnGREP.Common/DirectoryConfiguration.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/ReportWriter.cs
- dnGREP.Common/Utils.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/App.xaml.cs
- dnGREP.WPF/AppTheme.cs
- dnGREP.WPF/ConfigurationManager.cs
- dnGREP.WPF/Scripting/ScriptManager.cs
- dnGREP.WPF/ThemedHighlightingManager.cs
- dnGREP.WPF/ViewModels/BookmarksViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/MainViewModelScripts.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/ViewModels/ScriptViewModel.cs
- dnGREP.WPF/Views/MainView.xaml
- dnGREP.WPF/Views/OptionsView.xaml
Allow user to change the location of the settings and log directories.
> Directory config

- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/MVHelpers/EditorLocalization.cs
- dnGREP.WPF/Views/PreviewControl.xaml.cs
- dnGREP.WPF/Views/ReplaceWindow.xaml.cs
Introduce new localized strings in Resources.Designer.cs and Resources.resx for error and no matches found messages. Update PreviewControl.xaml.cs and ReplaceWindow.xaml.cs to use EditorLocalization for search panel localization. Add EditorLocalization class to provide localized text for search-related UI elements.
> Add localization support for search panel

- dnGREP.Common/CompareFolders.cs
- dnGREP.Common/DirectoryConfiguration.cs
- dnGREP.WPF/ConfigurationManager.cs
under the application directory
> fixs for copying to and from the themes directory 

- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/KeyBinding/KeyGestureLocalizer.cs
- dnGREP.WPF/ThemedControls/TextBox.xaml
- dnGREP.WPF/Views/KeyboardShortcutWindow.xaml.cs
- dnGREP.WPF/Views/OptionsView.xaml.cs
Exclude the menu key from shortcut keys
> Add translations for non-printing keys

- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/BookmarksViewModel.cs
- dnGREP.WPF/Views/BookmarksWindow.xaml
- dnGREP.WPF/Views/KeyboardShortcutWindow.xaml
Add menu labels for Bookmark context menu items
Unset user can delete in data grids
> Remove input gesture strings, create dynamically

- dnGREP.Localization/Properties/Resources.hr.resx
Currently translated at 19.9% (209 of 1047 strings)
Translate-URL: https://hosted.weblate.org/projects/dngrep/dngrep-application/hr/
> Translated using Weblate (Croatian)

- dnGREP.Common.UI/UiUtils.cs
- dnGREP.Common/GrepApplicationSettings.cs
- dnGREP.Common/PathSearchText.cs
- dnGREP.Localization/Properties/Resources.Designer.cs
- dnGREP.Localization/Properties/Resources.resx
- dnGREP.WPF/ViewModels/FormattedGrepResult.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
- dnGREP.WPF/ViewModels/OptionsViewModel.cs
- dnGREP.WPF/Views/OptionsView.xaml
Fix logic for using relative path based on common base path and add option to always show full path
> #1309 relative and full paths

- dnGREP.WPF/Views/MainView.xaml.cs
Use the restore keyboard shortcut to minimize the window if it is the active window
> Extend the restore keyboard shortcut

- dnGREP.Common/PathSearchText.cs
- dnGREP.WPF/ViewModels/FormattedGrepResult.cs
- dnGREP.WPF/ViewModels/MainViewModel.cs
> 1333 reset commonBaseFolder when changing search path
